kind: pipeline
type: kubernetes
name: build

steps:
  - name: install-deps
    image: python:3.12-slim
    commands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  - name: run-tests
    image: python:3.12-slim
    commands:
      - . venv/bin/activate
      - pytest