kind: pipeline
type: kubernetes
name: build

steps:
  - name: install-deps
    image: python:3.12-slim
    commands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  - name: run-tests
    image: python:3.12-slim
    environment:
      MONGO_URI: 
        from_secret: MONGO_URI
      MONGO_URI_READ:
        from_secret: MONGO_URI_READ
    commands:
      - . venv/bin/activate
      - pytest
        
  - name: apply-all-manifests
    image: bitnami/kubectl:latest
    environment:
      KUBECONFIG:
        from_secret: KUBECONFIG
    commands:
      - kubectl apply -f k8s/

  - name: build-and-push
    image: plugins/docker
    settings:
      repo: 192.168.68.137:30500/flask-app
      tags: latest