kind: pipeline
type: kubernetes
name: build

steps:
  - name: install-deps
    image: python:3.12-slim
    commands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  - name: run-tests
    image: python:3.12-slim
    environment:
      MONGO_URI: 
        from_secret: MONGO_URI
      MONGO_URI_READ:
        from_secret: MONGO_URI_READ
    commands:
      - . venv/bin/activate
      - pytest