name: servants-discovery

on:
  workflow_dispatch:

jobs:
  catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Run discovery catalog (verbose)
        env:
          MONGO_URI_READ: ${{ secrets.MONGO_URI_READ }}
        run: |
          python discovery_catalog.py --verbose > discovery_report.json

      - name: Upload discovery report
        uses: actions/upload-artifact@v4
        with:
          name: discovery-report
          path: discovery_report.json
