name: Discover Servants from R2

on:
  workflow_dispatch: {}

jobs:
  discover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run discovery
        id: run
        env:
          R2_ROOT_URL: ${{ secrets.R2_ROOT_URL }}
        run: |
          if [ -z "$R2_ROOT_URL" ]; then
            echo "ERROR: R2_ROOT_URL secret is not set" >&2
            exit 2
          fi
          python tools/discover_from_r2.py --r2-root "$R2_ROOT_URL" --out discovery_report.json --outdir downloaded_servants
          cat discovery_report.json

      - name: Upload discovery artifact
        uses: actions/upload-artifact@v4
        with:
          name: discovery-report
          path: discovery_report.json
